### PR TITLE
Readme and updated ipython notebook 

### PR DESCRIPTION
**Pull request by cavestruz**

### CODE REVIEW

**Review by matthewkirby — APPROVED** [review]
Small changes to sample ipynb and readme

**Review by aimalz — COMMENTED** [review]
This looks very reasonable, so I'm approving the changes.  (Sorry for not reviewing this sooner!)

**Comment by aimalz** [comment]
Awesome, folks!  I'm going to take this as the most recent version of the wishlist notebook and migrate it over to the separate repository for the rebooted code if no one objects.

**Review by aimalz — APPROVED** [review]
Whoops, I failed to approve before closing the PR.

**Pull request merged**
